# Generated by Django 6.0.1 on 2026-02-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_habitant", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=255)),
                ("date_emission", models.DateField(auto_now_add=True)),
                ("numero_certificat", models.CharField(max_length=20, unique=True)),
                (
                    "statut_paiement",
                    models.CharField(default="non payé", max_length=20),
                ),
            ],
        ),
    ]
